version: '2'

networks:
  whatsapp:
    driver: bridge

services:
  whatsapp-rest:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'ilhamfadhilah/whatsapp-rest:dev'
    container_name: 'whatsapp-rest'
    # entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - postgres
    networks:
      default:
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./dbs:/usr/app/go-whatsapp-multidevice-rest/dbs

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "0.0.0.0:32432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U postgres -d postgres',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      default:
  
