apiVersion: apps/v1
kind: Deployment
metadata:
  name: productzilla-whatsapp-rest
  namespace: default
  labels:
    app: whatsapp-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-rest
  template:
    metadata:
      labels:
        app: whatsapp-rest
    spec:
      containers:
        - name: whatsapp-rest
          image: ilhamfadhilah/whatsapp-rest:dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "3000"
            - name: HTTP_BASE_URL
              value: /api/v1/whatsapp
            - name: AUTH_BASIC_USERNAME
              value: root
            - name: AUTH_BASIC_PASSWORD
              value: ProductzillaCool123
            - name: AUTH_JWT_SECRET
              value: ThisIsJWTSecret
            - name: AUTH_JWT_EXPIRED_HOUR
              value: "48"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: productzilla-secret
                  key: postgresql-16-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: productzilla-secret
                  key: postgresql-16-port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: productzilla-password-secret
                  key: postgresql-16-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: productzilla-password-secret
                  key: postgresql-16-password
            - name: DB_NAME
              value: whatsapp-rest
            - name: WHATSAPP_DATASTORE_TYPE
              value: postgres
            - name: WHATSAPP_DATASTORE_URI
              value: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
            - name: WHATSAPP_CLIENT_PROXY_URL
              value: ""
            - name: WHATSAPP_MEDIA_IMAGE_COMPRESSION
              value: "true"
            - name: WHATSAPP_MEDIA_IMAGE_CONVERT_WEBP
              value: "true"
            - name: LIBWEBP_VERSION
              value: "0.6.1"
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-rest-svc
  namespace: default
spec:
  selector:
    app: whatsapp-rest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # should match containerPort
