x-app: &whatsapp-rest
  build:
    context: .
    dockerfile: ./Dockerfile
  image: 'ilhamfadhilah/whatsapp-rest:dev'
  depends_on:
    - postgres
  env_file:
    - ../../.env
  volumes:
    - ./volumes/dbs:/usr/app/go-whatsapp-multidevice-rest/dbs

services:
  whatsapp-rest-1:
    <<: *whatsapp-rest

  whatsapp-rest-2:
    <<: *whatsapp-rest

  whatsapp-rest-3:
    <<: *whatsapp-rest
