name: Semantic Release and Docker Publish

on:
  push:
    branches:
      - ignore-all

permissions:
  contents: write  # required to allow pushing tags & changelog updates

jobs:
  semantic-release:
    name: Semantic Release & Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed for semantic-release to analyze commits

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # built-in
        run: npx semantic-release

      - name: Get Latest Tag
        id: get_tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/git-webhook-node:${{ env.TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/git-webhook-node:${{ env.TAG }}
